### ISSUE TITLE
Validation and merging of Introductory Problems solutions 

### ISSUE THREAD

**Issue by Zeo-shark** [anushreeBera/cses-fi#2]
**I have added solution to some of the problems in the Introductory section of [*cses.fi*](cses.fi) it would be great if someone takes the initiative to validate and merge the pull requests.**
Author: [souravbera](https://github.com/Zeo-shark/)

**Comment by Zeo-shark** [comment]
#1 @anushreeBera kindly validate and merge it

**Comment by anushreeBera** [comment]
Not an issue, raise PR
